GET http://localhost:5173/api/names

###

POST http://localhost:5173/api/names
Content-Type: application/json

{
  "name": "OZ"
}

###

PUT http://localhost:5173/api/names
Content-Type: application/json

{
  "id": 4,
  "name": "Ester"
}

### 


DELETE http://localhost:5173/api/names
Content-Type: application/json

{
  "id": 5
}
