GET http://localhost:5173/api/names

###

POST http://localhost:5173/api/names
Content-Type: "application/json"

{
  "name": "Riosu"
}

###

PUT http://localhost:5173/api/names

### 


DELETE http://localhost:5173/api/names


